version: "3"

services:
  api:
    container_name: api-nestjs
    build: ./server
    command: npm run start:prod
    ports:
      - "3100:3100"
    env_file:
      - server/.env
    environment:
      - POSTGRES_HOST=db
    volumes:
      - ./server/client:/app/client
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: postgres-db-nestjs
    image: postgres:15.3-alpine
    env_file:
      - server/.env
    ports:
      - "5430:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped

  socket:
    container_name: socket-nestjs
    build: ./socket
    command: npm run start:prod
    env_file:
      - socket/.env
    ports:
      - "3200:3200"
    environment:
      - POSTGRES_HOST=db
    restart: unless-stopped
    depends_on:
      - db

  nginx:
    container_name: nginx-nestjs
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html

